x1=input("Hello There sir or ma'am! I need your first x value!")
x2=input("Alright thank you! Can I have your second x value?")
x3=input("I'm not sure you did that correctly... Though we have to move on third x value please.")
y1=input("Jeez you really don't know how to work this. Though the show must go on first y value please.")
y2=input("You know what I take back everything I said you clearly have never touched a computer before second y value please")
y3=input("Seriously? That's your second y value? Where did you learn math prison?")
thislist = []
Secondlist = []
thislist.append(x1)
thislist.append(x2)
thislist.append(x3)
Secondlist.append(y1)
Secondlist.append(y2)
Secondlist.append(y3)
print(thislist)    
print(Secondlist)
ready=input("Are you ready to see your coordinates? Or did you go back to prison?") 
print(thislist[0])
print(Secondlist[0])
ready1=input("Alright bud are you ready for the next set of coordinates?")
print(thislist[1])
print(Secondlist[1])
ready2=input("Alright prisoner are you ready for the last set?")
print(thislist[2])
print(Secondlist[2])
print("Thank you! You can now say you have touched a computer!")